### ISSUE TITLE
GSOC 2020 

### ISSUE THREAD

**Issue by priyansh19** [marmarek/qubes-builder-mirage#5]
Hello Sir,
I am Priyansh Gupta from India
I want to contribute in Qubes OS project this year in GSOC 2020
I will be needing you help regarding that

**Comment by marmarek** [comment]
Hello,
Take a look at https://www.qubes-os.org/gsoc/
First of all: write to the [qubes-devel](https://www.qubes-os.org/support/#qubes-devel) mailing list, not github issues.
